# worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"

[list]
json-schema = 2

[projects."github.com/sisu-connect/sisu-root"]
[projects."github.com/sisu-connect/sisu-root".step.copy-ignored]
exclude = ["node_modules/"]

[projects."github.com/sisu-connect/sisu-root".pre-start]
install = "pnpm install"

[projects."github.com/sisu-connect/sisu-root".post-start]
copy = "wt step copy-ignored"
build_essentials = "pnpm turbo build --filter=@sisu-connect/eslint-config"
